all:
	make -C CUL clean
	make -C CUL all
	find . -name \*.eep | xargs rm
	find . -name \*.elf | xargs rm
	find . -name \*.lss | xargs rm
	find . -name \*.lst | xargs rm
	find . -name \*.map | xargs rm
	find . -name \*.sym | xargs rm
	find . -name \*.o | xargs rm
